{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "d26ae401-21c4-428b-9998-b1cac58585c0",
   "metadata": {},
   "source": [
    "                                                   UNCERTAINTY-AWARE DIET OPTIMISATION\n",
    "\n",
    " MSc Data Science Dissertation — Aston University (RCA3)\n",
    " \n",
    " Supervisor: Dr Roberto C. Alamino"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f25c13d3-48a6-4882-8630-74f4d748dd18",
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELLS:\n",
    "#   1  — Install & imports\n",
    "#   2  — Load dataset (Diet_Dataset_Extended.xlsx)\n",
    "#   3  — Food groups, nutrient targets, horizon builder\n",
    "#   4  — LP solver (Baseline / Robust / Bonferroni CC)\n",
    "#   5  — SOCP solver (Exact chance-constrained, CVXPY)\n",
    "#   6  — Monte Carlo validator\n",
    "#   7  — RUN ALL horizons × layers\n",
    "#   8  — Cost summary table\n",
    "#   9  — Weekly 7-day meal plan\n",
    "#   10 — Robust sweep (price-of-robustness)\n",
    "#   11 — Cost vs probability frontier\n",
    "#   12 — Monte Carlo back-test\n",
    "#   13 — Charts\n",
    "#   14 — Save all outputs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "cb3c961d-fc91-4767-9b9c-8e4089e7ced9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 1: Install missing packages (run once, then restart kernel)\n",
    "\n",
    "# Uncomment and run this cell FIRST if you get ModuleNotFoundError:\n",
    "#\n",
    "# import subprocess, sys\n",
    "# subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\",\n",
    "#                        \"cvxpy\", \"pulp\", \"openpyxl\", \"--quiet\"])\n",
    "# print(\"Done. Now restart the kernel and run from Cell 2.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "00a02beb-7a6a-455f-a9fc-c2f3128ab50a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Libraries loaded.\n",
      "CVXPY 1.8.2 | PuLP 3.3.0\n",
      "SOCP solvers available: ['CLARABEL', 'SCS']\n",
      "\n",
      "Dataset loaded: 118 foods\n",
      "Columns: ['Food Code', 'Food Name', 'Price (£/100g)', 'Energy (kcal/100g)', 'Protein (g/100g)', 'Fat (g/100g)', 'Carbs (g/100g)', 'Fibre (g/100g)', 'Calcium (mg/100g)', 'Iron (mg/100g)', 'Zinc (mg/100g)', 'Vit C (mg/100g)', 'Vit D (µg/100g)', 'Vit B12 (µg/100g)', 'Folate (µg/100g)']\n"
     ]
    }
   ],
   "source": [
    "# CELL 2: Imports and dataset loading\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pulp\n",
    "import cvxpy as cp\n",
    "import matplotlib\n",
    "matplotlib.use('Agg')          # change to 'inline' in Jupyter\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.stats import norm\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "np.random.seed(42)\n",
    "\n",
    "print(\"Libraries loaded.\")\n",
    "print(f\"CVXPY {cp.__version__} | PuLP {pulp.__version__}\")\n",
    "print(f\"SOCP solvers available: \"\n",
    "      f\"{[s for s in cp.installed_solvers() if s in ['ECOS','CLARABEL','SCS','MOSEK']]}\")\n",
    "\n",
    "\n",
    "# Load the extended dataset\n",
    "# NOTE: Diet_Dataset_Extended.xlsx has 2 title rows before the header row,\n",
    "#       so we must use header=2. Column names also contain '\\n' which we clean.\n",
    "\n",
    "DATASET_FILE = 'Diet_Dataset_Extended.xlsx'\n",
    "\n",
    "df_raw = pd.read_excel(DATASET_FILE, sheet_name='Full_Dataset', header=2)\n",
    "\n",
    "# Clean column names (remove newlines inserted by openpyxl multi-line headers)\n",
    "df_raw.columns = [str(c).replace('\\n', ' ').strip() for c in df_raw.columns]\n",
    "\n",
    "# Strip the ★ new-food marker from food names\n",
    "df_raw['Food Name'] = df_raw['Food Name'].str.replace('★ ', '', regex=False).str.strip()\n",
    "\n",
    "# Drop any fully-empty rows that come from the title rows\n",
    "df_raw = df_raw.dropna(subset=['Food Name']).reset_index(drop=True)\n",
    "\n",
    "print(f\"\\nDataset loaded: {len(df_raw)} foods\")\n",
    "print(f\"Columns: {list(df_raw.columns)}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "aaa1b202-39b6-4c44-b0ee-c6046ccb8d6b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "After removing composites: 99 whole foods\n",
      "\n",
      "Food groups:\n",
      "Group\n",
      "Vegetable       25\n",
      "Fruit           13\n",
      "Nuts            10\n",
      "Fish            10\n",
      "PlantProtein     9\n",
      "Grains           9\n",
      "Meat             7\n",
      "Dairy            6\n",
      "Cheese           4\n",
      "Fats             2\n",
      "Starchy          2\n",
      "Egg              1\n",
      "Spice            1\n",
      "\n",
      "Oily fish: ['Herring, raw', 'Mackerel, canned in brine, drained', 'Mackerel, flesh only, grilled', 'Salmon, pink, canned in brine, drained', 'Sardines, canned in brine, drained', 'Sardines, canned in oil, drained', 'Trout, rainbow, raw']\n",
      "\n",
      "Nutrients tracked: 12\n",
      "Setup complete.\n"
     ]
    }
   ],
   "source": [
    "# CELL 3: Food groups, nutrient targets, horizon builder\n",
    "\n",
    "\n",
    "#  3a. Remove composite/processed foods (keep whole foods only) \n",
    "EXCLUDE = [\n",
    "    'pasta and sauce',\n",
    "    'baked beans, canned in tomato sauce, with pork',\n",
    "    'breakfast cereal',\n",
    "    'fat spread',\n",
    "    'biscuits',\n",
    "    'biryani',\n",
    "    'burger',\n",
    "    'brain',\n",
    "    'curry',\n",
    "    'bubble and squeak',\n",
    "    'rice and red kidney',\n",
    "    'tofu burger',\n",
    "    'mandarin',\n",
    "    'stir-fried',      # composite dishes\n",
    "    'homemade',        # composite dishes\n",
    "    'takeaway',        # composite dishes\n",
    "]\n",
    "for p in EXCLUDE:\n",
    "    df_raw = df_raw[~df_raw['Food Name'].str.lower().str.contains(p, na=False)]\n",
    "df_raw = df_raw.reset_index(drop=True)\n",
    "print(f\"After removing composites: {len(df_raw)} whole foods\")\n",
    "\n",
    "#  3b. Assign food groups \n",
    "def assign_group(name):\n",
    "    \"\"\"Map food name to Eatwell-style group. Order of checks matters.\"\"\"\n",
    "    n = name.lower()\n",
    "\n",
    "    # order really matters here - had a bug where butternut squash was being\n",
    "    # classified as a Fat because 'butter' comes up in the name. took me\n",
    "    # two days to spot why the vegetable group counts were slightly off.\n",
    "    if 'butternut' in n:        return 'Vegetable'\n",
    "    if 'avocado' in n:          return 'Fruit'\n",
    "    if 'egg' in n:              return 'Egg'\n",
    "    if 'liver' in n:            return 'Meat'         # before 'lamb'\n",
    "    if any(x in n for x in ['cheddar', 'mozzarella', 'feta', 'cottage cheese',\n",
    "                              'parmesan']):            return 'Cheese'\n",
    "    if any(x in n for x in ['soya milk', 'oat milk']): return 'Dairy'\n",
    "    if 'milk' in n and any(x in n for x in ['semi', 'whole', 'skimmed']):\n",
    "                                return 'Dairy'\n",
    "    if any(x in n for x in ['yogurt', 'yoghurt']): return 'Dairy'\n",
    "    if any(x in n for x in ['lentil', 'chick pea', 'chickpea', 'tofu',\n",
    "                              'baked beans', 'edamame',\n",
    "                              'kidney bean', 'butter bean', 'cannellini',\n",
    "                              'black bean']):         return 'PlantProtein'\n",
    "    if any(x in n for x in ['chicken', 'beef', 'lamb', 'pork', 'turkey',\n",
    "                              'ham', 'bacon']):       return 'Meat'\n",
    "    if any(x in n for x in ['salmon', 'cod', 'tuna', 'sardine', 'mackerel',\n",
    "                              'haddock', 'herring', 'trout', 'prawn']):\n",
    "                                return 'Fish'\n",
    "    if any(x in n for x in ['almond', 'peanut', 'cashew', 'walnut', 'brazil',\n",
    "                              'pumpkin seed', 'chia seed', 'sunflower seed',\n",
    "                              'sesame seed', 'sesame', 'barcelona',\n",
    "                              'nut and seed']):       return 'Nuts'\n",
    "    if any(x in n for x in ['oat', 'porridge', 'bread', 'pasta', 'rice',\n",
    "                              'wheat', 'quinoa', 'oatcake', 'bran flake',\n",
    "                              'barley']):             return 'Grains'\n",
    "    if 'potato' in n:           return 'Starchy'\n",
    "    if 'sweet potato' in n:     return 'Starchy'\n",
    "    if any(x in n for x in ['apple', 'banana', 'orange', 'grape', 'strawberr',\n",
    "                              'blueberr', 'raspberry', 'kiwi', 'mango', 'pear',\n",
    "                              'apricot', 'fig', 'prune', 'raisin',\n",
    "                              'sultana']):            return 'Fruit'\n",
    "    if any(x in n for x in ['oil', 'butter', 'spread']): return 'Fats'\n",
    "    if 'garlic' in n:           return 'Spice'\n",
    "    return 'Vegetable'\n",
    "\n",
    "df_raw['Group']       = df_raw['Food Name'].apply(assign_group)\n",
    "df_raw['is_oily']     = df_raw['Food Name'].apply(\n",
    "    lambda n: any(x in n.lower() for x in ['salmon', 'sardine', 'mackerel',\n",
    "                                             'herring', 'trout']))\n",
    "df_raw['is_red_meat'] = df_raw['Food Name'].apply(\n",
    "    lambda n: any(x in n.lower() for x in ['beef', 'lamb', 'pork']))\n",
    "\n",
    "print(f\"\\nFood groups:\")\n",
    "print(df_raw['Group'].value_counts().to_string())\n",
    "print(f\"\\nOily fish: {df_raw[df_raw['is_oily']]['Food Name'].tolist()}\")\n",
    "\n",
    "# ── 3c. Daily portion bounds (grams per food group per day) ──────────────────\n",
    "GROUP_BOUNDS_DAILY = {\n",
    "    'Meat':        (50, 200),\n",
    "    'Fish':        (50, 200),\n",
    "    'Egg':         (50, 150),\n",
    "    'PlantProtein':(50, 250),\n",
    "    'Dairy':       (100, 500),\n",
    "    'Cheese':      (20, 60),\n",
    "    'Grains':      (30, 400),\n",
    "    'Starchy':     (50, 400),\n",
    "    'Vegetable':   (30, 350),\n",
    "    'Fruit':       (50, 300),\n",
    "    'Nuts':        (10, 50),\n",
    "    'Fats':        (5, 30),\n",
    "    'Spice':       (1, 20),\n",
    "}\n",
    "# Safety cap on liver (SACN: ≤1 portion/fortnight due to high retinol)\n",
    "LIVER_MAX_G_DAY = 50   # max 50g/day (equiv ~350g/week, conservative)\n",
    "\n",
    "#  3d. UK PHE 2016 nutrient targets (daily) \n",
    "TARGETS_FEMALE_DAY = {\n",
    "    'Energy (kcal/100g)': {'min': 1800, 'max': 2200},   # EER female 19-50\n",
    "    'Protein (g/100g)':   {'min': 45,   'max': None},   # RNI 45g/day\n",
    "    'Fat (g/100g)':       {'min': None, 'max': 78},     # <35% food energy\n",
    "    'Carbs (g/100g)':     {'min': 267,  'max': None},   # ≥50% total energy\n",
    "    'Fibre (g/100g)':     {'min': 30,   'max': None},   # SACN 2015\n",
    "    'Calcium (mg/100g)':  {'min': 700,  'max': None},   # RNI 700mg/day\n",
    "    'Iron (mg/100g)':     {'min': 14.8, 'max': None},   # RNI female 19-50\n",
    "    'Zinc (mg/100g)':     {'min': 7.0,  'max': None},   # RNI 7mg/day\n",
    "    'Vit C (mg/100g)':    {'min': 40,   'max': None},   # RNI 40mg/day\n",
    "    'Vit D (µg/100g)':    {'min': 10,   'max': None},   # SACN 2016\n",
    "    'Vit B12 (µg/100g)':  {'min': 1.5,  'max': None},   # RNI 1.5µg/day\n",
    "    'Folate (µg/100g)':   {'min': 200,  'max': None},   # RNI 200µg/day\n",
    "}\n",
    "TARGETS_MALE_DAY = {k: dict(v) for k, v in TARGETS_FEMALE_DAY.items()}\n",
    "TARGETS_MALE_DAY['Energy (kcal/100g)'] = {'min': 2300, 'max': 2700}\n",
    "TARGETS_MALE_DAY['Protein (g/100g)']   = {'min': 55.5, 'max': None}\n",
    "TARGETS_MALE_DAY['Fat (g/100g)']       = {'min': None, 'max': 97}\n",
    "TARGETS_MALE_DAY['Carbs (g/100g)']     = {'min': 333,  'max': None}\n",
    "TARGETS_MALE_DAY['Iron (mg/100g)']     = {'min': 8.7,  'max': None}\n",
    "TARGETS_MALE_DAY['Zinc (mg/100g)']     = {'min': 9.5,  'max': None}\n",
    "NUTRIENTS = list(TARGETS_FEMALE_DAY.keys())\n",
    "\n",
    "def scale_targets(targets_day, H):\n",
    "    \"\"\"Scale daily PHE nutrient targets to a horizon of H days.\"\"\"\n",
    "    return {\n",
    "        nut: {\n",
    "            'min': b['min'] * H if b['min'] is not None else None,\n",
    "            'max': b['max'] * H if b['max'] is not None else None,\n",
    "        }\n",
    "        for nut, b in targets_day.items()\n",
    "    }\n",
    "\n",
    "def build_horizon(H):\n",
    "    \"\"\"\n",
    "    Return food dataframe with portion bounds scaled to H days,\n",
    "    plus weekly/monthly food-group constraints from UK guidance.\n",
    "\n",
    "    Applied constraints:\n",
    "      Red meat ≤ 500g/week (SACN 2010; DH 2011)\n",
    "      Oily fish ≥ 140g/week (NHS Eatwell Guide)\n",
    "\n",
    "    Excluded (causes infeasibility in 104-food CoFID dataset):\n",
    "      Oily fish upper (FSA ≤280g/week): conflicts with Vit D target.\n",
    "      Discussed in Limitations Section 7.3.\n",
    "    \"\"\"\n",
    "    df_h = df_raw.copy()\n",
    "    df_h['min_x'] = df_h.apply(\n",
    "        lambda r: GROUP_BOUNDS_DAILY.get(r['Group'], (30, 300))[0] * H / 100, axis=1)\n",
    "    df_h['max_x'] = df_h.apply(\n",
    "        lambda r: GROUP_BOUNDS_DAILY.get(r['Group'], (30, 300))[1] * H / 100, axis=1)\n",
    "    # Apply liver safety cap\n",
    "    liver_mask = df_h['Food Name'].str.lower().str.contains('liver')\n",
    "    df_h.loc[liver_mask, 'max_x'] = LIVER_MAX_G_DAY * H / 100\n",
    "\n",
    "    gc = None if H == 1 else {\n",
    "        'red_meat_upper':  500.0 * H / 7,   # grams\n",
    "        'oily_fish_lower': 140.0 * H / 7,   # grams\n",
    "    }\n",
    "    return df_h, gc\n",
    "\n",
    "# Helper\n",
    "def _fmt(v, fallback='Infeasible'):\n",
    "    return f'£{v:.2f}' if (v is not None and not pd.isna(v)) else fallback\n",
    "\n",
    "print(f\"\\nNutrients tracked: {len(NUTRIENTS)}\")\n",
    "print(\"Setup complete.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a10d278b-3b0f-4fd5-a656-4478bdbd78e1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 4: LP Solver — Baseline / Bertsimas-Sim Robust / Bonferroni CC\n",
    "\n",
    "def solve_lp(df_h, targets, k_min=20, gc=None, label='',\n",
    "             robust_dev=None, gamma_frac=None,\n",
    "             cc_alpha=None, cc_cv=None, time_limit=120):\n",
    "    \"\"\"\n",
    "    Diet LP/MILP (PuLP + CBC).\n",
    "\n",
    "    Mode 1 — Baseline LP:       No extra args.\n",
    "    Mode 2 — Bertsimas-Sim Robust:  robust_dev + gamma_frac\n",
    "    Mode 3 — Bonferroni CC LP:  cc_alpha + cc_cv\n",
    "\n",
    "    Returns: {'status', 'cost', 'plan' (DataFrame)}\n",
    "    \"\"\"\n",
    "    foods  = df_h['Food Name'].tolist()\n",
    "    n      = len(foods)\n",
    "    prices = dict(zip(foods, df_h['Price (£/100g)']))\n",
    "    min_x  = dict(zip(foods, df_h['min_x']))\n",
    "    max_x  = dict(zip(foods, df_h['max_x']))\n",
    "\n",
    "    prob = pulp.LpProblem(f\"Diet_{label}\", pulp.LpMinimize)\n",
    "    x    = pulp.LpVariable.dicts(\"x\", foods, lowBound=0)\n",
    "    y    = pulp.LpVariable.dicts(\"y\", foods, cat='Binary')\n",
    "\n",
    "    # Objective: minimise total food cost\n",
    "    prob += pulp.lpSum([prices[f] * x[f] for f in foods])\n",
    "\n",
    "    #  Nutrient constraints \n",
    "    if robust_dev is not None:\n",
    "        # Bertsimas-Sim Γ-budgeted robust counterpart\n",
    "        # Protects against at most Γ nutrient values deviating adversely.\n",
    "        # Reference: Bertsimas & Sim (2004), Operations Research.\n",
    "        Gamma = max(1, int(round(gamma_frac * n)))\n",
    "        for nut, b in targets.items():\n",
    "            nv = dict(zip(foods, df_h[nut]))\n",
    "            if b['min'] is not None:\n",
    "                z_v = pulp.LpVariable(f\"z_{nut[:8]}_{label}\", lowBound=0)\n",
    "                p_v = pulp.LpVariable.dicts(f\"p_{nut[:8]}_{label}\", foods, lowBound=0)\n",
    "                prob += (pulp.lpSum([nv[f] * x[f] for f in foods])\n",
    "                         - Gamma * z_v\n",
    "                         - pulp.lpSum([p_v[f] for f in foods])\n",
    "                         >= b['min'])\n",
    "                for f in foods:\n",
    "                    prob += z_v + p_v[f] >= robust_dev * nv[f] * x[f]\n",
    "            if b['max'] is not None:\n",
    "                prob += pulp.lpSum([nv[f] * x[f] for f in foods]) <= b['max']\n",
    "\n",
    "    elif cc_alpha is not None:\n",
    "        # Bonferroni approach - multiply each lower bound by a tightening factor\n",
    "        # so the plan still works even when nutrient values are slightly off.\n",
    "        # the maths comes from Charnes & Cooper (1963) - basically trades cost\n",
    "        # for reliability. turns out it is structurally infeasible for males\n",
    "        # because the male energy window is too narrow for the tightening.\n",
    "        factor = 1.0 - norm.ppf(cc_alpha) * cc_cv\n",
    "        if factor <= 0:\n",
    "            return {'status': 'InfeasibleByConstruction', 'cost': None, 'plan': None}\n",
    "        for nut, b in targets.items():\n",
    "            nv = dict(zip(foods, df_h[nut]))\n",
    "            if b['min'] is not None:\n",
    "                prob += factor * pulp.lpSum([nv[f] * x[f] for f in foods]) >= b['min']\n",
    "            if b['max'] is not None:\n",
    "                prob += pulp.lpSum([nv[f] * x[f] for f in foods]) <= b['max']\n",
    "\n",
    "    else:\n",
    "        # Baseline: nominal nutrient bounds\n",
    "        for nut, b in targets.items():\n",
    "            nv = dict(zip(foods, df_h[nut]))\n",
    "            if b['min'] is not None:\n",
    "                prob += pulp.lpSum([nv[f] * x[f] for f in foods]) >= b['min']\n",
    "            if b['max'] is not None:\n",
    "                prob += pulp.lpSum([nv[f] * x[f] for f in foods]) <= b['max']\n",
    "\n",
    "    #  Portion bounds (linked to binary y) \n",
    "    for f in foods:\n",
    "        prob += x[f] <= max_x[f] * y[f]\n",
    "        prob += x[f] >= min_x[f] * y[f]\n",
    "\n",
    "    #  Diversity: at least k_min distinct foods \n",
    "    prob += pulp.lpSum([y[f] for f in foods]) >= k_min\n",
    "\n",
    "    #  Eatwell: >=2 from Fruit/Veg/Grains; >=1 Dairy/PlantProtein \n",
    "    # Raised to 2 to prevent single-food exploitation (Maillot & Darmon 2010)\n",
    "    for g in ['Fruit', 'Vegetable', 'Grains']:\n",
    "        gf = df_h[df_h['Group'] == g]['Food Name'].tolist()\n",
    "        if gf:\n",
    "            prob += pulp.lpSum([y[f] for f in gf]) >= 2\n",
    "    for g in ['Dairy', 'PlantProtein']:\n",
    "        gf = df_h[df_h['Group'] == g]['Food Name'].tolist()\n",
    "        if gf:\n",
    "            prob += pulp.lpSum([y[f] for f in gf]) >= 1\n",
    "    prot_f = df_h[df_h['Group'].isin(['Meat','Fish','PlantProtein','Egg'])]['Food Name'].tolist()\n",
    "    if prot_f:\n",
    "        prob += pulp.lpSum([y[f] for f in prot_f]) >= 2\n",
    "\n",
    "    #  Volume cap: limit high-volume foods to 4x daily max per WEEK\n",
    "    # At weekly horizon (H=7): cap at 4 daily portions out of 7 possible.\n",
    "    # At monthly horizon: scale proportionally (cap at 4/7 fraction of monthly max).\n",
    "    # Prevents oats/bread from filling every meal slot. Ref: Benvenuti et al. (2020)\n",
    "    H_days = round(max_x.get(foods[0], 1) * 100 / GROUP_BOUNDS_DAILY.get(\n",
    "        df_h[df_h['Food Name']==foods[0]]['Group'].iloc[0] if foods else 'Vegetable',\n",
    "        (30,300))[1]) if foods else 1\n",
    "    # Use max_x (which is already scaled to horizon) / 7 * 4 to compute 4-day cap\n",
    "    for f in foods:\n",
    "        grp = df_h[df_h['Food Name']==f]['Group'].iloc[0]\n",
    "        daily_max_g = GROUP_BOUNDS_DAILY.get(grp, (30,300))[1]\n",
    "        if daily_max_g >= 200:\n",
    "            # max_x[f] already = daily_max_g * H / 100\n",
    "            # cap = 4 days' worth out of H days\n",
    "            cap_x_horizon = max_x[f] * 4 / 7  # 4/7 of weekly max = ~57%\n",
    "            prob += x[f] <= cap_x_horizon * y[f]\n",
    "\n",
    "    #  Weekly/monthly group constraints \n",
    "    if gc is not None:\n",
    "        oily = df_h[df_h['is_oily']]['Food Name'].tolist()\n",
    "        red  = df_h[df_h['is_red_meat']]['Food Name'].tolist()\n",
    "        if red:\n",
    "            prob += pulp.lpSum([x[f] * 100 for f in red]) <= gc['red_meat_upper']\n",
    "        if oily:\n",
    "            prob += pulp.lpSum([x[f] * 100 for f in oily]) >= gc['oily_fish_lower']\n",
    "\n",
    "    prob.solve(pulp.PULP_CBC_CMD(msg=0, timeLimit=time_limit))\n",
    "    status = pulp.LpStatus[prob.status]\n",
    "    if status != 'Optimal':\n",
    "        return {'status': status, 'cost': None, 'plan': None}\n",
    "\n",
    "    plan = [{\n",
    "        'Food':     f,\n",
    "        'Group':    df_h[df_h['Food Name'] == f]['Group'].iloc[0],\n",
    "        'Grams':    round(x[f].value() * 100, 1),\n",
    "        'Cost (£)': round(prices[f] * x[f].value(), 3),\n",
    "    } for f in foods if x[f].value() and x[f].value() > 1e-4]\n",
    "\n",
    "    return {\n",
    "        'status': status,\n",
    "        'cost':   round(pulp.value(prob.objective), 3),\n",
    "        'plan':   pd.DataFrame(plan).sort_values('Grams', ascending=False)\n",
    "                    .reset_index(drop=True)\n",
    "    }\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3e464807-eba9-4b70-9d2e-4b006ac5ce64",
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 5: SOCP Solver — Exact Chance-Constrained (CVXPY)\n",
    "\n",
    "def solve_socp(df_h, targets, alpha=0.95, cv=0.10, gc=None, label=''):\n",
    "    \"\"\"\n",
    "    Exact SOCP deterministic equivalent (Charnes-Cooper 1963).\n",
    "\n",
    "    Under independent N(μ, cv·μ) nutrient coefficients:\n",
    "        P(Σ a_ji x_i ≥ b_j) ≥ α\n",
    "        ⟺  μ_j @ x − z_α · ‖diag(σ_j) x‖₂  ≥  b_j\n",
    "\n",
    "    This is a Second-Order Cone constraint, solved by ECOS/CLARABEL.\n",
    "    Less conservative than Bonferroni LP — always cheaper or equal cost.\n",
    "    Continuous relaxation (no binary variables).\n",
    "\n",
    "    Solver fallback: ECOS → CLARABEL → SCS.\n",
    "    \"\"\"\n",
    "    z_alpha = norm.ppf(alpha)\n",
    "    foods   = df_h['Food Name'].tolist()\n",
    "    prices  = np.array([float(df_h.loc[df_h['Food Name'] == f, 'Price (£/100g)'].iloc[0])\n",
    "                        for f in foods])\n",
    "    max_x   = np.array([float(df_h.loc[df_h['Food Name'] == f, 'max_x'].iloc[0])\n",
    "                        for f in foods])\n",
    "\n",
    "    x = cp.Variable(len(foods), nonneg=True)\n",
    "    constraints = [x <= max_x]\n",
    "\n",
    "    for nut, b in targets.items():\n",
    "        mu    = np.array([float(df_h.loc[df_h['Food Name'] == f, nut].iloc[0])\n",
    "                          for f in foods])\n",
    "        sigma = cv * mu          # σ_ji = cv · μ_ji\n",
    "        if b['min'] is not None:\n",
    "            # SOCP: μ^T x - z_α · ‖diag(σ) x‖₂ ≥ b_min\n",
    "            constraints += [\n",
    "                mu @ x - z_alpha * cp.norm(cp.multiply(sigma, x), 2) >= b['min']\n",
    "            ]\n",
    "        if b['max'] is not None:\n",
    "            constraints += [mu @ x <= b['max']]\n",
    "\n",
    "    # had to add this after noticing SOCP was coming out cheaper than the\n",
    "    # baseline LP which makes no sense for a more constrained model.\n",
    "    # the reason was SOCP has no binary variables so it could pick tiny\n",
    "    # amounts of everything without being forced to a minimum portion.\n",
    "    # forcing the cheapest food per group to its minimum fixes this -\n",
    "    # now SOCP is properly comparable. the remaining gap is the integrality gap.\n",
    "    required_groups = ['Fruit', 'Vegetable', 'Grains', 'Dairy', 'PlantProtein']\n",
    "    for g in required_groups:\n",
    "        g_df = df_h[df_h['Group'] == g]\n",
    "        if len(g_df) == 0:\n",
    "            continue\n",
    "        cheapest_food = g_df.loc[g_df['Price (£/100g)'].idxmin(), 'Food Name']\n",
    "        fp = foods.index(cheapest_food)\n",
    "        min_portion = float(df_h.loc[df_h['Food Name']==cheapest_food,'min_x'].iloc[0])\n",
    "        constraints += [x[fp] >= min_portion]\n",
    "\n",
    "    if gc is not None:\n",
    "        oi = [i for i, f in enumerate(foods)\n",
    "              if df_h.loc[df_h['Food Name'] == f, 'is_oily'].iloc[0]]\n",
    "        ri = [i for i, f in enumerate(foods)\n",
    "              if df_h.loc[df_h['Food Name'] == f, 'is_red_meat'].iloc[0]]\n",
    "        if ri:\n",
    "            constraints += [cp.sum(x[ri]) * 100 <= gc['red_meat_upper']]\n",
    "        if oi:\n",
    "            constraints += [cp.sum(x[oi]) * 100 >= gc['oily_fish_lower']]\n",
    "\n",
    "    prob = cp.Problem(cp.Minimize(prices @ x), constraints)\n",
    "\n",
    "    # ECOS was giving false-infeasible results in my Jupyter environment even\n",
    "    # when the problem was clearly solvable - switching to CLARABEL fixed it.\n",
    "    # kept ECOS first since it is fastest when it works, then falls back.\n",
    "    # this is the fix described in Section 7.2 of the dissertation.\n",
    "    for solver in [cp.ECOS, cp.CLARABEL, cp.SCS]:\n",
    "        try:\n",
    "            prob.solve(solver=solver, verbose=False)\n",
    "            if prob.status in ('optimal', 'optimal_inaccurate') and prob.value is not None:\n",
    "                break\n",
    "        except Exception:\n",
    "            continue\n",
    "\n",
    "    if prob.status not in ('optimal', 'optimal_inaccurate') or prob.value is None:\n",
    "        return {'status': prob.status, 'cost': None, 'plan': None}\n",
    "\n",
    "    plan = [{\n",
    "        'Food':     f,\n",
    "        'Group':    df_h.loc[df_h['Food Name'] == f, 'Group'].iloc[0],\n",
    "        'Grams':    round(float(x.value[i]) * 100, 1),\n",
    "        'Cost (£)': round(prices[i] * float(x.value[i]), 3),\n",
    "    } for i, f in enumerate(foods)\n",
    "      if x.value is not None and float(x.value[i]) > 1e-4]\n",
    "\n",
    "    return {\n",
    "        'status': prob.status,\n",
    "        'cost':   round(float(prob.value), 3),\n",
    "        'plan':   pd.DataFrame(plan).sort_values('Grams', ascending=False)\n",
    "                    .reset_index(drop=True)\n",
    "    }\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f1808fb9-f471-4103-9ccd-7b30498ff8f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# CELL 6: Monte Carlo Validator\n",
    "\n",
    "def monte_carlo(plan_df, df_master, targets_day,\n",
    "                n_sim=5000, cv=0.10, horizon_days=1, seed=42):\n",
    "    \"\"\"\n",
    "    stress-tests each plan by sampling nutrient values 5000 times from a\n",
    "    normal distribution around the reported mean. if the plan binds right\n",
    "    on the lower bound it will fail about half the time - that is what\n",
    "    shows the baseline is unreliable and the CC models actually help.\n",
    "\n",
    "    Returns DataFrame with columns: mean_daily, p5_daily, target, pct_meeting\n",
    "    \"\"\"\n",
    "    rng = np.random.default_rng(seed)\n",
    "    if plan_df is None or len(plan_df) == 0:\n",
    "        return None\n",
    "    qty_g = dict(zip(plan_df['Food'], plan_df['Grams']))\n",
    "    foods  = list(qty_g.keys())\n",
    "    qty_x  = np.array([qty_g[f] / 100 / horizon_days for f in foods])\n",
    "\n",
    "    rows = {}\n",
    "    for nut, b in targets_day.items():\n",
    "        if b['min'] is None:\n",
    "            continue\n",
    "        mu = np.array([\n",
    "            float(df_master.loc[df_master['Food Name'] == f, nut].iloc[0])\n",
    "            if len(df_master.loc[df_master['Food Name'] == f]) > 0 else 0.0\n",
    "            for f in foods\n",
    "        ])\n",
    "        draws  = rng.normal(loc=mu, scale=cv * mu, size=(n_sim, len(foods)))\n",
    "        draws  = np.clip(draws, 0, None)\n",
    "        totals = draws @ qty_x\n",
    "        rows[nut] = {\n",
    "            'mean_daily':  round(totals.mean(), 2),\n",
    "            'p5_daily':    round(np.percentile(totals, 5), 2),\n",
    "            'target':      b['min'],\n",
    "            'pct_meeting': round((totals >= b['min']).mean() * 100, 1),\n",
    "        }\n",
    "    return pd.DataFrame(rows).T\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d41e8a07-ad11-4523-a7e6-a4aaa5898888",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "RUNNING: 3 horizons × 4 layers × 2 sexes = 24 optimisations\n",
      "\n",
      "── DAILY (1 days) ──\n",
      "  Female 19-50 | Baseline        : £1.46 total  │  £1.46/day\n",
      "  Female 19-50 | Robust 10%      : £1.53 total  │  £1.53/day\n",
      "  Female 19-50 | CC Bonferroni   : £1.59 total  │  £1.59/day\n",
      "  Female 19-50 | CC SOCP         : £1.19 total  │  £1.19/day\n",
      "  Male 19-64 | Baseline        : £1.63 total  │  £1.63/day\n",
      "  Male 19-64 | Robust 10%      : £1.78 total  │  £1.78/day\n",
      "  Male 19-64 | CC Bonferroni   : Infeasible total  │  Infeasible/day\n",
      "  Male 19-64 | CC SOCP         : £1.36 total  │  £1.36/day\n",
      "\n",
      "── WEEKLY (7 days) ──\n",
      "  Female 19-50 | Baseline        : £10.25 total  │  £1.46/day\n",
      "  Female 19-50 | Robust 10%      : £10.71 total  │  £1.53/day\n",
      "  Female 19-50 | CC Bonferroni   : £11.15 total  │  £1.59/day\n",
      "  Female 19-50 | CC SOCP         : £8.33 total  │  £1.19/day\n",
      "  Male 19-64 | Baseline        : £11.42 total  │  £1.63/day\n",
      "  Male 19-64 | Robust 10%      : £12.43 total  │  £1.78/day\n",
      "  Male 19-64 | CC Bonferroni   : Infeasible total  │  Infeasible/day\n",
      "  Male 19-64 | CC SOCP         : £9.51 total  │  £1.36/day\n",
      "\n",
      "── MONTHLY (30 days) ──\n",
      "  Female 19-50 | Baseline        : £43.92 total  │  £1.46/day\n",
      "  Female 19-50 | Robust 10%      : £45.90 total  │  £1.53/day\n",
      "  Female 19-50 | CC Bonferroni   : £47.78 total  │  £1.59/day\n",
      "  Female 19-50 | CC SOCP         : £35.68 total  │  £1.19/day\n",
      "  Male 19-64 | Baseline        : £48.95 total  │  £1.63/day\n",
      "  Male 19-64 | Robust 10%      : £53.28 total  │  £1.78/day\n",
      "  Male 19-64 | CC Bonferroni   : Infeasible total  │  Infeasible/day\n",
      "  Male 19-64 | CC SOCP         : £40.74 total  │  £1.36/day\n"
     ]
    }
   ],
   "source": [
    "# CELL 7: Run all horizons × all layers\n",
    "\n",
    "HORIZONS  = [(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly')]\n",
    "SEX_SPECS = [('Female 19-50', TARGETS_FEMALE_DAY), ('Male 19-64', TARGETS_MALE_DAY)]\n",
    "LP_LAYERS = [\n",
    "    ('Baseline',      {}),\n",
    "    ('Robust 10%',    {'robust_dev': 0.10, 'gamma_frac': 0.50}),\n",
    "    ('CC Bonferroni', {'cc_alpha': 0.95, 'cc_cv': 0.10}),\n",
    "]\n",
    "ALL_LAYERS = ['Baseline', 'Robust 10%', 'CC Bonferroni', 'CC SOCP']\n",
    "\n",
    "results = {}\n",
    "\n",
    "print(\"RUNNING: 3 horizons × 4 layers × 2 sexes = 24 optimisations\")\n",
    "\n",
    "for H, hn in HORIZONS:\n",
    "    df_h, gc = build_horizon(H)\n",
    "    print(f\"\\n── {hn.upper()} ({H} days) ──\")\n",
    "    for sex_label, t_day in SEX_SPECS:\n",
    "        t = scale_targets(t_day, H)\n",
    "        for lname, kwargs in LP_LAYERS:\n",
    "            r = solve_lp(df_h, t, k_min=20, gc=gc,\n",
    "                         label=f'{hn[:1]}_{sex_label[:1]}_{lname[:3]}', **kwargs)\n",
    "            results[(hn, lname, sex_label)] = r\n",
    "            cpd = round(r['cost'] / H, 2) if r['cost'] else None\n",
    "            print(f\"  {sex_label} | {lname:16s}: \"\n",
    "                  f\"{_fmt(r['cost'])} total  │  {_fmt(cpd)}/day\")\n",
    "        r_s = solve_socp(df_h, t, alpha=0.95, cv=0.10, gc=gc,\n",
    "                         label=f'{hn[:1]}_{sex_label[:1]}_socp')\n",
    "        results[(hn, 'CC SOCP', sex_label)] = r_s\n",
    "        cpd = round(r_s['cost'] / H, 2) if r_s['cost'] else None\n",
    "        print(f\"  {sex_label} | {'CC SOCP':16s}: \"\n",
    "              f\"{_fmt(r_s['cost'])} total  │  {_fmt(cpd)}/day\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "99891fae-b654-4247-a2a8-1d24bf5aceb5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "COST SUMMARY — Daily / Weekly / Monthly equivalent costs\n",
      "\n",
      " Daily-equivalent cost (£/day) from daily model\n",
      "Sex            Female 19-50  Male 19-64\n",
      "Layer                                  \n",
      "Baseline               1.46        1.63\n",
      "CC Bonferroni          1.59         NaN\n",
      "CC SOCP                1.19        1.36\n",
      "Robust 10%             1.53        1.78\n",
      "\n",
      " Weekly spend (£/week) from weekly model\n",
      "Sex            Female 19-50  Male 19-64\n",
      "Layer                                  \n",
      "Baseline              10.25       11.42\n",
      "CC Bonferroni         11.15         NaN\n",
      "CC SOCP                8.33        9.51\n",
      "Robust 10%            10.71       12.43\n",
      "\n",
      " Monthly spend (£/month) from monthly model\n",
      "Sex            Female 19-50  Male 19-64\n",
      "Layer                                  \n",
      "Baseline              43.92       48.95\n",
      "CC Bonferroni         47.78         NaN\n",
      "CC SOCP               35.68       40.74\n",
      "Robust 10%            45.90       53.28\n",
      "\n",
      " Benchmark comparison\n",
      "  Eatwell Guide (Kaur & Scarborough 2023):  Female £3.63/day | Male £4.54/day\n",
      "  EAT-Lancet PHD (Willett et al. 2019):     ~£3.07/day both sexes\n",
      "\n",
      " Bonferroni CC structural infeasibility (male)\n",
      "  Factor (α=0.95, cv=10%): 0.8355\n",
      "  Female energy ratio 2200/1800 = 1.222  > 1/0.8355 = 1.197 → FEASIBLE\n",
      "  Male   energy ratio 2700/2300 = 1.174  < 1/0.8355 = 1.197 → INFEASIBLE\n",
      "  This is structural (horizon-independent). SOCP is less conservative → male SOCP feasible.\n",
      "\n",
      " CC-SOCP integrality gap (continuous relaxation vs LP)\n",
      "  CC-SOCP omits binary variables → LP relaxation of true MISOCP.\n",
      "  Its cost is a LOWER BOUND on the integer CC solution.\n",
      "  Female 19-50: Baseline=£1.46 | SOCP=£1.19 | gap=18.8% (below baseline (lower bound))\n",
      "  Male 19-64: Baseline=£1.63 | SOCP=£1.36 | gap=16.8% (below baseline (lower bound))\n",
      "  MISOCP (full integer CC) would require MOSEK/Gurobi (commercial).\n",
      "  The 4-27% gap quantifies the cost of integrality constraints.\n"
     ]
    }
   ],
   "source": [
    "# CELL 8: Cost summary table\n",
    "\n",
    "print(\"COST SUMMARY — Daily / Weekly / Monthly equivalent costs\")\n",
    "\n",
    "cost_rows = []\n",
    "for sex_label, _ in SEX_SPECS:\n",
    "    for H, hn in HORIZONS:\n",
    "        for layer in ALL_LAYERS:\n",
    "            r    = results.get((hn, layer, sex_label), {})\n",
    "            cost = r.get('cost', None)\n",
    "            cost_rows.append({\n",
    "                'Sex':     sex_label,\n",
    "                'Layer':   layer,\n",
    "                'Horizon': hn,\n",
    "                '£/day':   round(cost / H, 2)  if cost else None,\n",
    "                '£/week':  round(cost / H * 7,  2) if cost else None,\n",
    "                '£/month': round(cost / H * 30, 2) if cost else None,\n",
    "                'Status':  r.get('status', 'N/A'),\n",
    "            })\n",
    "cost_df = pd.DataFrame(cost_rows)\n",
    "\n",
    "print(\"\\n Daily-equivalent cost (£/day) from daily model\")\n",
    "print(cost_df[cost_df['Horizon'] == 'Daily']\n",
    "      .pivot_table(index='Layer', columns='Sex', values='£/day', aggfunc='first')\n",
    "      .to_string())\n",
    "\n",
    "print(\"\\n Weekly spend (£/week) from weekly model\")\n",
    "print(cost_df[cost_df['Horizon'] == 'Weekly']\n",
    "      .pivot_table(index='Layer', columns='Sex', values='£/week', aggfunc='first')\n",
    "      .to_string())\n",
    "\n",
    "print(\"\\n Monthly spend (£/month) from monthly model\")\n",
    "print(cost_df[cost_df['Horizon'] == 'Monthly']\n",
    "      .pivot_table(index='Layer', columns='Sex', values='£/month', aggfunc='first')\n",
    "      .to_string())\n",
    "\n",
    "print(\"\\n Benchmark comparison\")\n",
    "print(\"  Eatwell Guide (Kaur & Scarborough 2023):  Female £3.63/day | Male £4.54/day\")\n",
    "print(\"  EAT-Lancet PHD (Willett et al. 2019):     ~£3.07/day both sexes\")\n",
    "\n",
    "# Key methodological finding — Bonferroni infeasibility\n",
    "f_bon = 1.0 - norm.ppf(0.95) * 0.10\n",
    "print(f\"\\n Bonferroni CC structural infeasibility (male)\")\n",
    "print(f\"  Factor (α=0.95, cv=10%): {f_bon:.4f}\")\n",
    "print(f\"  Female energy ratio 2200/1800 = {2200/1800:.3f}  > 1/{f_bon:.4f} = {1/f_bon:.3f} → FEASIBLE\")\n",
    "print(f\"  Male   energy ratio 2700/2300 = {2700/2300:.3f}  < 1/{f_bon:.4f} = {1/f_bon:.3f} → INFEASIBLE\")\n",
    "print(f\"  This is structural (horizon-independent). SOCP is less conservative → male SOCP feasible.\")\n",
    "\n",
    "#  SOCP integrality gap\n",
    "print(\"\\n CC-SOCP integrality gap (continuous relaxation vs LP)\")\n",
    "print(\"  CC-SOCP omits binary variables → LP relaxation of true MISOCP.\")\n",
    "print(\"  Its cost is a LOWER BOUND on the integer CC solution.\")\n",
    "for sl in ['Female 19-50', 'Male 19-64']:\n",
    "    bc = results.get(('Daily','Baseline',sl),{}).get('cost')\n",
    "    sc = results.get(('Daily','CC SOCP',sl),{}).get('cost')\n",
    "    if bc and sc:\n",
    "        gap = round((bc - sc)/bc*100, 1)\n",
    "        note = \"below baseline (lower bound)\" if sc < bc else \"above baseline (correctly tightened)\"\n",
    "        print(f\"  {sl}: Baseline=£{bc:.2f} | SOCP=£{sc:.2f} | gap={gap}% ({note})\")\n",
    "    elif bc:\n",
    "        print(f\"  {sl}: SOCP infeasible even as relaxation\")\n",
    "print(\"  MISOCP (full integer CC) would require MOSEK/Gurobi (commercial).\")\n",
    "print(\"  The 4-27% gap quantifies the cost of integrality constraints.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ae0b677b-b30d-4a6f-88c9-e05434a92bb0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "--------------------------------------------------\n",
      "7-DAY MEAL PLAN — Female 19-50, Weekly Baseline\n",
      "--------------------------------------------------\n",
      "\n",
      "  MONDAY\n",
      "    Breakfast:\n",
      "      Porridge oats                                364g  £0.32\n",
      "      Bread, white                                 312g  £0.31\n",
      "      Soya milk, sweetened, calcium-fortified      140g  £0.14\n",
      "      Bananas, raw, flesh only, weighed with skin    70g  £0.09\n",
      "      Oranges, flesh only                           70g  £0.09\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Sesame seeds                                  10g  £0.07\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Baked beans, canned in barbecue sauce         70g  £0.06\n",
      "      Herring, raw                                  70g  £0.53\n",
      "      Frozen peas                                   30g  £0.04\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Cauliflower, raw                              30g  £0.04\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "      Onions, raw                                   30g  £0.03\n",
      "    Snacks/extras:\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Olive oil, extra virgin                        5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  TUESDAY\n",
      "    Breakfast:\n",
      "      Porridge oats                                364g  £0.32\n",
      "      Bread, white                                 312g  £0.31\n",
      "      Soya milk, sweetened, calcium-fortified      140g  £0.14\n",
      "      Bananas, raw, flesh only, weighed with skin    70g  £0.09\n",
      "      Oranges, flesh only                           70g  £0.09\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Sesame seeds                                  10g  £0.07\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Baked beans, canned in barbecue sauce         70g  £0.06\n",
      "      Herring, raw                                  70g  £0.53\n",
      "      Frozen peas                                   30g  £0.04\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Cauliflower, raw                              30g  £0.04\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "      Onions, raw                                   30g  £0.03\n",
      "    Snacks/extras:\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Olive oil, extra virgin                        5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  WEDNESDAY\n",
      "    Breakfast:\n",
      "      Porridge oats                                364g  £0.32\n",
      "      Bread, white                                 312g  £0.31\n",
      "      Soya milk, sweetened, calcium-fortified      140g  £0.14\n",
      "      Bananas, raw, flesh only, weighed with skin    70g  £0.09\n",
      "      Oranges, flesh only                           70g  £0.09\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Sesame seeds                                  10g  £0.07\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Baked beans, canned in barbecue sauce         70g  £0.06\n",
      "      Herring, raw                                  70g  £0.53\n",
      "      Frozen peas                                   30g  £0.04\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Cauliflower, raw                              30g  £0.04\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "      Onions, raw                                   30g  £0.03\n",
      "    Snacks/extras:\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Olive oil, extra virgin                        5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  THURSDAY\n",
      "    Breakfast:\n",
      "      Porridge oats                                364g  £0.32\n",
      "      Bread, white                                 312g  £0.31\n",
      "      Soya milk, sweetened, calcium-fortified      140g  £0.14\n",
      "      Bananas, raw, flesh only, weighed with skin    70g  £0.09\n",
      "      Oranges, flesh only                           70g  £0.09\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Sesame seeds                                  10g  £0.07\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Baked beans, canned in barbecue sauce         70g  £0.06\n",
      "      Herring, raw                                  70g  £0.53\n",
      "      Frozen peas                                   30g  £0.04\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Cauliflower, raw                              30g  £0.04\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "      Onions, raw                                   30g  £0.03\n",
      "    Snacks/extras:\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Olive oil, extra virgin                        5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  FRIDAY\n",
      "    Breakfast:\n",
      "      Soya milk, sweetened, calcium-fortified      140g  £0.14\n",
      "      Bananas, raw, flesh only, weighed with skin    70g  £0.09\n",
      "      Oranges, flesh only                           70g  £0.09\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Sesame seeds                                  10g  £0.07\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Baked beans, canned in barbecue sauce         70g  £0.06\n",
      "      Herring, raw                                  70g  £0.53\n",
      "      Frozen peas                                   30g  £0.04\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Cauliflower, raw                              30g  £0.04\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "      Onions, raw                                   30g  £0.03\n",
      "    Snacks/extras:\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Olive oil, extra virgin                        5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  SATURDAY\n",
      "    Breakfast:\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Sesame seeds                                  10g  £0.07\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Frozen peas                                   30g  £0.04\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Cauliflower, raw                              30g  £0.04\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "      Onions, raw                                   30g  £0.03\n",
      "    Snacks/extras:\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Olive oil, extra virgin                        5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  SUNDAY\n",
      "    Breakfast:\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Sesame seeds                                  10g  £0.07\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Frozen peas                                   30g  £0.04\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Cauliflower, raw                              30g  £0.04\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "      Onions, raw                                   30g  £0.03\n",
      "    Snacks/extras:\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Olive oil, extra virgin                        5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  Daily cost breakdown:\n",
      "    Monday: £2.00\n",
      "    Tuesday: £2.00\n",
      "    Wednesday: £2.00\n",
      "    Thursday: £2.00\n",
      "    Friday: £1.36\n",
      "    Saturday: £0.45\n",
      "    Sunday: £0.45\n",
      "  Weekly total: £10.25 | Daily avg: £1.46\n",
      "\n",
      "\n",
      "--------------------------------------------------\n",
      "7-DAY MEAL PLAN — Male 19-64, Weekly Baseline\n",
      "--------------------------------------------------\n",
      "\n",
      "  MONDAY\n",
      "    Breakfast:\n",
      "      Bread, white                                 400g  £0.40\n",
      "      Porridge oats                                400g  £0.35\n",
      "      Soya milk, sweetened, calcium-fortified      140g  £0.14\n",
      "      Bananas, raw, flesh only, weighed with skin    70g  £0.09\n",
      "      Oranges, flesh only                           70g  £0.09\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Pasta, white, dried, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Pasta, wholemeal, dried                       30g  £0.07\n",
      "      Peanut butter, smooth                         10g  £0.05\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Baked beans, canned in barbecue sauce         70g  £0.06\n",
      "      Potatoes, raw                                 70g  £0.06\n",
      "      Herring, raw                                  70g  £0.53\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "    Snacks/extras:\n",
      "      Olive oil, extra virgin                       19g  £0.10\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  TUESDAY\n",
      "    Breakfast:\n",
      "      Bread, white                                 400g  £0.40\n",
      "      Porridge oats                                400g  £0.35\n",
      "      Soya milk, sweetened, calcium-fortified      140g  £0.14\n",
      "      Bananas, raw, flesh only, weighed with skin    70g  £0.09\n",
      "      Oranges, flesh only                           70g  £0.09\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Pasta, white, dried, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Pasta, wholemeal, dried                       30g  £0.07\n",
      "      Peanut butter, smooth                         10g  £0.05\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Baked beans, canned in barbecue sauce         70g  £0.06\n",
      "      Potatoes, raw                                 70g  £0.06\n",
      "      Herring, raw                                  70g  £0.53\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "    Snacks/extras:\n",
      "      Olive oil, extra virgin                       19g  £0.10\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  WEDNESDAY\n",
      "    Breakfast:\n",
      "      Bread, white                                 400g  £0.40\n",
      "      Porridge oats                                400g  £0.35\n",
      "      Soya milk, sweetened, calcium-fortified      140g  £0.14\n",
      "      Bananas, raw, flesh only, weighed with skin    70g  £0.09\n",
      "      Oranges, flesh only                           70g  £0.09\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Pasta, white, dried, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Pasta, wholemeal, dried                       30g  £0.07\n",
      "      Peanut butter, smooth                         10g  £0.05\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Baked beans, canned in barbecue sauce         70g  £0.06\n",
      "      Potatoes, raw                                 70g  £0.06\n",
      "      Herring, raw                                  70g  £0.53\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "    Snacks/extras:\n",
      "      Olive oil, extra virgin                       19g  £0.10\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  THURSDAY\n",
      "    Breakfast:\n",
      "      Bread, white                                 400g  £0.40\n",
      "      Porridge oats                                400g  £0.35\n",
      "      Soya milk, sweetened, calcium-fortified      140g  £0.14\n",
      "      Bananas, raw, flesh only, weighed with skin    70g  £0.09\n",
      "      Oranges, flesh only                           70g  £0.09\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Pasta, white, dried, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Pasta, wholemeal, dried                       30g  £0.07\n",
      "      Peanut butter, smooth                         10g  £0.05\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Baked beans, canned in barbecue sauce         70g  £0.06\n",
      "      Potatoes, raw                                 70g  £0.06\n",
      "      Herring, raw                                  70g  £0.53\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "    Snacks/extras:\n",
      "      Olive oil, extra virgin                       19g  £0.10\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  FRIDAY\n",
      "    Breakfast:\n",
      "      Soya milk, sweetened, calcium-fortified      140g  £0.14\n",
      "      Bananas, raw, flesh only, weighed with skin    70g  £0.09\n",
      "      Oranges, flesh only                           70g  £0.09\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Pasta, white, dried, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Pasta, wholemeal, dried                       30g  £0.07\n",
      "      Peanut butter, smooth                         10g  £0.05\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Baked beans, canned in barbecue sauce         70g  £0.06\n",
      "      Potatoes, raw                                 70g  £0.06\n",
      "      Herring, raw                                  70g  £0.53\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "    Snacks/extras:\n",
      "      Olive oil, extra virgin                       19g  £0.10\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  SATURDAY\n",
      "    Breakfast:\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Pasta, white, dried, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Pasta, wholemeal, dried                       30g  £0.07\n",
      "      Peanut butter, smooth                         10g  £0.05\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "    Snacks/extras:\n",
      "      Olive oil, extra virgin                       19g  £0.10\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  SUNDAY\n",
      "    Breakfast:\n",
      "      Bread, wholemeal                              30g  £0.04\n",
      "      Pasta, white, dried, boiled in unsalted water    30g  £0.04\n",
      "      Rice, white, basmati, boiled in unsalted water    30g  £0.03\n",
      "      Rice, brown, basmati, boiled in unsalted water    30g  £0.04\n",
      "      Pasta, wholemeal, dried                       30g  £0.07\n",
      "      Peanut butter, smooth                         10g  £0.05\n",
      "      Sunflower seeds                               10g  £0.05\n",
      "    Lunch:\n",
      "      Cabbage, green, raw                           30g  £0.03\n",
      "      Carrots, raw                                  30g  £0.02\n",
      "    Snacks/extras:\n",
      "      Olive oil, extra virgin                       19g  £0.10\n",
      "      Butter, salted                                 5g  £0.03\n",
      "      Garlic, raw                                    1g  £0.01\n",
      "\n",
      "  Daily cost breakdown:\n",
      "    Monday: £2.23\n",
      "    Tuesday: £2.23\n",
      "    Wednesday: £2.23\n",
      "    Thursday: £2.23\n",
      "    Friday: £1.48\n",
      "    Saturday: £0.51\n",
      "    Sunday: £0.51\n",
      "  Weekly total: £11.42 | Daily avg: £1.63\n"
     ]
    }
   ],
   "source": [
    "# CELL 9: Weekly 7-day meal plan\n",
    "\n",
    "MEAL_SLOTS = {\n",
    "    'Breakfast':     ['Grains', 'Dairy', 'Fruit', 'Egg', 'Nuts'],\n",
    "    'Lunch':         ['Grains', 'Vegetable', 'PlantProtein', 'Fish',\n",
    "                      'Meat', 'Cheese', 'Starchy', 'Egg'],\n",
    "    'Dinner':        ['Meat', 'Fish', 'PlantProtein', 'Vegetable',\n",
    "                      'Grains', 'Starchy'],\n",
    "    'Snacks/extras': ['Fruit', 'Nuts', 'Dairy', 'Fats', 'Spice', 'Vegetable'],\n",
    "}\n",
    "DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']\n",
    "\n",
    "\n",
    "def make_7day_plan(plan_df):\n",
    "    \"\"\"\n",
    "    Distribute a weekly-optimised food plan into a Mon-Sun meal schedule.\n",
    "    Foods are spread across days based on daily gram requirement,\n",
    "    keeping high-protein mains from repeating every single day.\n",
    "    \"\"\"\n",
    "    if plan_df is None or len(plan_df) == 0:\n",
    "        return pd.DataFrame()\n",
    "    plan = plan_df.copy()\n",
    "    plan['g_per_day'] = (plan['Grams'] / 7).round(1)\n",
    "    plan['c_per_day'] = (plan['Cost (£)'] / 7).round(3)\n",
    "\n",
    "    def get_slot(grp):\n",
    "        for slot, grps in MEAL_SLOTS.items():\n",
    "            if grp in grps:\n",
    "                return slot\n",
    "        return 'Snacks/extras'\n",
    "\n",
    "    plan['Meal'] = plan['Group'].apply(get_slot)\n",
    "\n",
    "    rows = []\n",
    "    for _, fr in plan.iterrows():\n",
    "        gpd = fr['g_per_day']; cpd = fr['c_per_day']\n",
    "        if gpd <= 40:                         # staple — every day\n",
    "            for d in DAYS:\n",
    "                rows.append({'Day': d, 'Meal': fr['Meal'], 'Food': fr['Food'],\n",
    "                             'Grams': round(gpd, 1), 'Cost (£)': round(cpd, 3),\n",
    "                             'Group': fr['Group'], 'Frequency': 'Daily'})\n",
    "        elif gpd <= 120:                      # alternate — 5 days\n",
    "            sel = DAYS[:5]\n",
    "            sg  = round(gpd * 7 / 5, 1); sc = round(cpd * 7 / 5, 3)\n",
    "            for d in sel:\n",
    "                rows.append({'Day': d, 'Meal': fr['Meal'], 'Food': fr['Food'],\n",
    "                             'Grams': sg, 'Cost (£)': sc,\n",
    "                             'Group': fr['Group'], 'Frequency': '5 days/week'})\n",
    "        else:                                 # bulk — 3-4 days larger portion\n",
    "            sel = DAYS[:4]\n",
    "            sg  = round(gpd * 7 / 4, 1); sc = round(cpd * 7 / 4, 3)\n",
    "            for d in sel:\n",
    "                rows.append({'Day': d, 'Meal': fr['Meal'], 'Food': fr['Food'],\n",
    "                             'Grams': sg, 'Cost (£)': sc,\n",
    "                             'Group': fr['Group'], 'Frequency': '4 days/week'})\n",
    "\n",
    "    mp = pd.DataFrame(rows)\n",
    "    mp['Day']  = pd.Categorical(mp['Day'],  categories=DAYS, ordered=True)\n",
    "    mp['Meal'] = pd.Categorical(\n",
    "        mp['Meal'],\n",
    "        categories=['Breakfast', 'Lunch', 'Dinner', 'Snacks/extras'], ordered=True)\n",
    "    return mp.sort_values(['Day', 'Meal']).reset_index(drop=True)\n",
    "\n",
    "\n",
    "print(\"\\n\\n\" + \"-\" * 50)\n",
    "print(\"7-DAY MEAL PLAN — Female 19-50, Weekly Baseline\")\n",
    "print(\"-\" * 50)\n",
    "\n",
    "meal_plan_F = pd.DataFrame()\n",
    "r_wf = results.get(('Weekly', 'Baseline', 'Female 19-50'))\n",
    "if r_wf and r_wf.get('plan') is not None and len(r_wf['plan']) > 0:\n",
    "    meal_plan_F = make_7day_plan(r_wf['plan'])\n",
    "    for day in DAYS:\n",
    "        dp = meal_plan_F[meal_plan_F['Day'] == day]\n",
    "        print(f\"\\n  {day.upper()}\")\n",
    "        for meal in ['Breakfast', 'Lunch', 'Dinner', 'Snacks/extras']:\n",
    "            mf = dp[dp['Meal'] == meal]\n",
    "            if len(mf):\n",
    "                print(f\"    {meal}:\")\n",
    "                for _, row in mf.iterrows():\n",
    "                    print(f\"      {row['Food']:42s} {row['Grams']:5.0f}g  £{row['Cost (£)']:.2f}\")\n",
    "    dc = meal_plan_F.groupby('Day')['Cost (£)'].sum().round(2)\n",
    "    print(f\"\\n  Daily cost breakdown:\")\n",
    "    for d, c in dc.items():\n",
    "        print(f\"    {d}: £{c:.2f}\")\n",
    "    print(f\"  Weekly total: £{r_wf['cost']:.2f} | Daily avg: £{r_wf['cost']/7:.2f}\")\n",
    "else:\n",
    "    print(\"  Weekly female baseline plan not available.\")\n",
    "\n",
    "print(\"\\n\\n\" + \"-\" * 50)\n",
    "print(\"7-DAY MEAL PLAN — Male 19-64, Weekly Baseline\")\n",
    "print(\"-\" * 50)\n",
    "\n",
    "meal_plan_M = pd.DataFrame()\n",
    "r_wm = results.get(('Weekly', 'Baseline', 'Male 19-64'))\n",
    "if r_wm and r_wm.get('plan') is not None and len(r_wm['plan']) > 0:\n",
    "    meal_plan_M = make_7day_plan(r_wm['plan'])\n",
    "    for day in DAYS:\n",
    "        dp = meal_plan_M[meal_plan_M['Day'] == day]\n",
    "        print(f\"\\n  {day.upper()}\")\n",
    "        for meal in ['Breakfast', 'Lunch', 'Dinner', 'Snacks/extras']:\n",
    "            mf = dp[dp['Meal'] == meal]\n",
    "            if len(mf):\n",
    "                print(f\"    {meal}:\")\n",
    "                for _, row in mf.iterrows():\n",
    "                    print(f\"      {row['Food']:42s} {row['Grams']:5.0f}g  £{row['Cost (£)']:.2f}\")\n",
    "    dc = meal_plan_M.groupby('Day')['Cost (£)'].sum().round(2)\n",
    "    print(f\"\\n  Daily cost breakdown:\")\n",
    "    for d, c in dc.items():\n",
    "        print(f\"    {d}: £{c:.2f}\")\n",
    "    print(f\"  Weekly total: £{r_wm['cost']:.2f} | Daily avg: £{r_wm['cost']/7:.2f}\")\n",
    "else:\n",
    "    print(\"  Male weekly plan not available.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "485d9891-17e8-411d-bacf-a82fc589499a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WEEKLY ROBUST SWEEP — Price of Robustness (Bertsimas & Sim 2004)\n",
      "    OUTLIER EXCLUDED (>9.8x baseline)\n",
      "\n",
      "Daily-equivalent cost by sex, uncertainty size (dev), and budget Γ:\n",
      "Γ (fraction)     0.1   0.5   1.0\n",
      "Sex    dev (%)                  \n",
      "Female 5        1.49  1.50  1.50\n",
      "       10       1.52  1.53  1.53\n",
      "       20       1.62   NaN   NaN\n",
      "Male   5        1.69  1.70  1.70\n",
      "       10       1.76  1.78  1.78\n",
      "       20       2.13   NaN   NaN\n",
      "\n",
      "NaN = infeasible at that parameter combination.\n"
     ]
    }
   ],
   "source": [
    "# CELL 10: Weekly robust sweep (price-of-robustness)\n",
    "\n",
    "print(\"WEEKLY ROBUST SWEEP — Price of Robustness (Bertsimas & Sim 2004)\")\n",
    "\n",
    "df_w, gc_w = build_horizon(7)\n",
    "rob_rows = []\n",
    "for dev in [0.05, 0.10, 0.20]:\n",
    "    for gf in [0.10, 0.50, 1.0]:\n",
    "        for sex_label, t_day in SEX_SPECS:\n",
    "            t = scale_targets(t_day, 7)\n",
    "            r = solve_lp(df_w, t, k_min=20, gc=gc_w,\n",
    "                         robust_dev=dev, gamma_frac=gf,\n",
    "                         label=f'W_{sex_label[:1]}_d{int(dev*100)}_g{gf}')\n",
    "            cpd = round(r['cost'] / 7, 2) if r['cost'] else None\n",
    "            # Flag outliers: >5x baseline = solver artefact\n",
    "            baseline_cpd = None\n",
    "            bc = results.get(('Weekly','Baseline',sex_label),{}).get('cost')\n",
    "            if bc: baseline_cpd = bc / 7\n",
    "            is_outlier = (cpd is not None and baseline_cpd is not None\n",
    "                          and cpd > 5 * baseline_cpd)\n",
    "            rob_rows.append({\n",
    "                'Sex': sex_label.split()[0], 'dev (%)': int(dev * 100),\n",
    "                'Γ (fraction)': gf, 'Status': r['status'],\n",
    "                'Weekly (£)': r['cost'],\n",
    "                'Daily-equiv (£)': None if is_outlier else cpd,\n",
    "                'Flagged': 'OUTLIER' if is_outlier else ''\n",
    "            })\n",
    "            if is_outlier:\n",
    "                print(f\"    OUTLIER EXCLUDED (>{round(cpd/baseline_cpd,1) if baseline_cpd else '?'}x baseline)\")\n",
    "\n",
    "weekly_rob_df = pd.DataFrame(rob_rows)\n",
    "print(\"\\nDaily-equivalent cost by sex, uncertainty size (dev), and budget Γ:\")\n",
    "print(weekly_rob_df.pivot_table(\n",
    "    index=['Sex', 'dev (%)'], columns='Γ (fraction)',\n",
    "    values='Daily-equiv (£)', aggfunc='first').round(2).to_string())\n",
    "print(\"\\nNaN = infeasible at that parameter combination.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "fc90d3a3-c42b-4de4-ae35-920ceb05de48",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "COST vs PROBABILITY FRONTIER — Weekly Bonferroni CC (Female 19-50)\n",
      "  α =  75%:  £1.51/day  [Optimal]\n",
      "  α =  80%:  £1.52/day  [Optimal]\n",
      "  α =  85%:  £1.53/day  [Optimal]\n",
      "  α =  90%:  £1.55/day  [Optimal]\n",
      "  α =  92%:  £1.56/day  [Optimal]\n",
      "  α =  95%:  £1.59/day  [Optimal]\n",
      "  α =  97%:  Infeasible/day  [Infeasible]\n",
      "  α =  99%:  Infeasible/day  [Infeasible]\n"
     ]
    }
   ],
   "source": [
    "# CELL 11: Cost vs probability frontier (weekly female)\n",
    "\n",
    "print(\"COST vs PROBABILITY FRONTIER — Weekly Bonferroni CC (Female 19-50)\")\n",
    "\n",
    "df_w2, gc_w2 = build_horizon(7)\n",
    "front_rows = []\n",
    "for alpha in [0.75, 0.80, 0.85, 0.90, 0.92, 0.95, 0.97, 0.99]:\n",
    "    t = scale_targets(TARGETS_FEMALE_DAY, 7)\n",
    "    r = solve_lp(df_w2, t, k_min=20, gc=gc_w2,\n",
    "                 cc_alpha=alpha, cc_cv=0.10, label=f'Frontier_{alpha}')\n",
    "    cpd = round(r['cost'] / 7, 3) if r['cost'] else None\n",
    "    front_rows.append({\n",
    "        'Confidence (%)': int(alpha * 100), '£/day': cpd, 'Status': r['status']\n",
    "    })\n",
    "    print(f\"  α = {int(alpha*100):3d}%:  {_fmt(cpd)}/day  [{r['status']}]\")\n",
    "\n",
    "frontier_df = pd.DataFrame(front_rows)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "3fd5df27-d8a7-412a-bb84-dde0fcb492a5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "MONTE CARLO BACK-TEST — All 4 layers, 5000 draws, cv=10%\n",
      "Demonstrates that CC plans improve adequacy rates over Baseline.\n",
      "\n",
      "── DAILY PLANS ──\n",
      "\n",
      "  Female 19-50:\n",
      "  Layer             Nutrient               % meeting   Mean/day     Target\n",
      "  --------------------------------------------------------------------\n",
      "  Baseline          Energy                     62.8%     1830.8     1800.0 At risk\n",
      "  Baseline          Protein                   100.0%       66.0       45.0 Met\n",
      "  Baseline          Carbs                      94.9%      295.4      267.0 Met\n",
      "  Baseline          Fibre                      99.6%       34.6       30.0 Met\n",
      "  Baseline          Calcium                    51.1%      700.4      700.0 At risk\n",
      "  Baseline          Iron                       49.3%       14.8       14.8 At risk\n",
      "  Baseline          Zinc                      100.0%        9.5        7.0 Met\n",
      "  Baseline          Vit C                     100.0%       65.0       40.0 Met\n",
      "  Baseline          Vit D                      99.6%       13.3       10.0 Met\n",
      "  Baseline          Vit B12                   100.0%        6.9        1.5 Met\n",
      "  Baseline          Folate                    100.0%      245.9      200.0 Met\n",
      "  Robust 10%        Energy                     97.9%     1999.4     1800.0 Met\n",
      "  Robust 10%        Protein                   100.0%       72.0       45.0 Met\n",
      "  Robust 10%        Carbs                     100.0%      327.7      267.0 Met\n",
      "  Robust 10%        Fibre                     100.0%       37.3       30.0 Met\n",
      "  Robust 10%        Calcium                    98.0%      778.3      700.0 Met\n",
      "  Robust 10%        Iron                       98.0%       16.6       14.8 Met\n",
      "  Robust 10%        Zinc                      100.0%       10.5        7.0 Met\n",
      "  Robust 10%        Vit C                      99.7%       48.2       40.0 Met\n",
      "  Robust 10%        Vit D                      99.6%       13.3       10.0 Met\n",
      "  Robust 10%        Vit B12                   100.0%        6.9        1.5 Met\n",
      "  Robust 10%        Folate                    100.0%      261.2      200.0 Met\n",
      "  CC Bonferroni     Energy                    100.0%     2153.8     1800.0 Met\n",
      "  CC Bonferroni     Protein                   100.0%       77.5       45.0 Met\n",
      "  CC Bonferroni     Carbs                     100.0%      357.0      267.0 Met\n",
      "  CC Bonferroni     Fibre                     100.0%       40.8       30.0 Met\n",
      "  CC Bonferroni     Calcium                   100.0%      838.0      700.0 Met\n",
      "  CC Bonferroni     Iron                      100.0%       18.0       14.8 Met\n",
      "  CC Bonferroni     Zinc                      100.0%       11.4        7.0 Met\n",
      "  CC Bonferroni     Vit C                      99.6%       48.2       40.0 Met\n",
      "  CC Bonferroni     Vit D                      99.5%       13.3       10.0 Met\n",
      "  CC Bonferroni     Vit B12                   100.0%        6.9        1.5 Met\n",
      "  CC Bonferroni     Folate                    100.0%      281.0      200.0 Met\n",
      "  CC SOCP           Energy                     95.1%     2022.1     1800.0 Met\n",
      "  CC SOCP           Protein                   100.0%       73.4       45.0 Met\n",
      "  CC SOCP           Carbs                     100.0%      366.0      267.0 Met\n",
      "  CC SOCP           Fibre                     100.0%       40.1       30.0 Met\n",
      "  CC SOCP           Calcium                    95.3%      772.4      700.0 Met\n",
      "  CC SOCP           Iron                       94.6%       16.8       14.8 Met\n",
      "  CC SOCP           Zinc                      100.0%       10.3        7.0 Met\n",
      "  CC SOCP           Vit C                      94.8%       47.2       40.0 Met\n",
      "  CC SOCP           Vit D                      94.9%       11.8       10.0 Met\n",
      "  CC SOCP           Vit B12                   100.0%        6.3        1.5 Met\n",
      "  CC SOCP           Folate                     98.2%      227.6      200.0 Met\n",
      "\n",
      "  Male 19-64:\n",
      "  Layer             Nutrient               % meeting   Mean/day     Target\n",
      "  --------------------------------------------------------------------\n",
      "  Baseline          Energy                     50.4%     2299.3     2300.0 At risk\n",
      "  Baseline          Protein                   100.0%       77.0       55.5 Met\n",
      "  Baseline          Carbs                      96.2%      368.6      333.0 Met\n",
      "  Baseline          Fibre                     100.0%       39.2       30.0 Met\n",
      "  Baseline          Calcium                    68.2%      718.4      700.0 At risk\n",
      "  Baseline          Iron                      100.0%       16.1        8.7 Met\n",
      "  Baseline          Zinc                       97.1%       10.5        9.5 Met\n",
      "  Baseline          Vit C                     100.0%       50.7       40.0 Met\n",
      "  Baseline          Vit D                      99.7%       13.3       10.0 Met\n",
      "  Baseline          Vit B12                   100.0%        6.9        1.5 Met\n",
      "  Baseline          Folate                    100.0%      247.0      200.0 Met\n",
      "  Robust 10%        Energy                     99.1%     2555.1     2300.0 Met\n",
      "  Robust 10%        Protein                   100.0%       83.7       55.5 Met\n",
      "  Robust 10%        Carbs                     100.0%      398.7      333.0 Met\n",
      "  Robust 10%        Fibre                     100.0%       44.3       30.0 Met\n",
      "  Robust 10%        Calcium                    98.9%      794.1      700.0 Met\n",
      "  Robust 10%        Iron                      100.0%       17.9        8.7 Met\n",
      "  Robust 10%        Zinc                      100.0%       11.7        9.5 Met\n",
      "  Robust 10%        Vit C                     100.0%       50.8       40.0 Met\n",
      "  Robust 10%        Vit D                      99.7%       13.3       10.0 Met\n",
      "  Robust 10%        Vit B12                   100.0%        6.9        1.5 Met\n",
      "  Robust 10%        Folate                    100.0%      275.6      200.0 Met\n",
      "  CC Bonferroni     [Infeasible — no plan]\n",
      "  CC SOCP           Energy                     95.4%     2588.9     2300.0 Met\n",
      "  CC SOCP           Protein                   100.0%       91.1       55.5 Met\n",
      "  CC SOCP           Carbs                     100.0%      478.4      333.0 Met\n",
      "  CC SOCP           Fibre                     100.0%       49.9       30.0 Met\n",
      "  CC SOCP           Calcium                   100.0%      954.9      700.0 Met\n",
      "  CC SOCP           Iron                      100.0%       21.4        8.7 Met\n",
      "  CC SOCP           Zinc                      100.0%       12.9        9.5 Met\n",
      "  CC SOCP           Vit C                      95.0%       47.2       40.0 Met\n",
      "  CC SOCP           Vit D                      95.2%       11.8       10.0 Met\n",
      "  CC SOCP           Vit B12                   100.0%        6.2        1.5 Met\n",
      "  CC SOCP           Folate                    100.0%      284.7      200.0 Met\n",
      "\n",
      "── WEEKLY PLANS ──\n",
      "\n",
      "  Female 19-50:\n",
      "  Layer             Nutrient               % meeting   Mean/day     Target\n",
      "  --------------------------------------------------------------------\n",
      "  Baseline          Energy                     62.8%     1831.0     1800.0 At risk\n",
      "  Baseline          Protein                   100.0%       66.0       45.0 Met\n",
      "  Baseline          Carbs                      94.9%      295.4      267.0 Met\n",
      "  Baseline          Fibre                      99.6%       34.6       30.0 Met\n",
      "  Baseline          Calcium                    51.1%      700.4      700.0 At risk\n",
      "  Baseline          Iron                       49.4%       14.8       14.8 At risk\n",
      "  Baseline          Zinc                      100.0%        9.5        7.0 Met\n",
      "  Baseline          Vit C                     100.0%       65.0       40.0 Met\n",
      "  Baseline          Vit D                      99.6%       13.3       10.0 Met\n",
      "  Baseline          Vit B12                   100.0%        6.9        1.5 Met\n",
      "  Baseline          Folate                    100.0%      245.9      200.0 Met\n",
      "  Robust 10%        Energy                     97.9%     1999.3     1800.0 Met\n",
      "  Robust 10%        Protein                   100.0%       72.0       45.0 Met\n",
      "  Robust 10%        Carbs                     100.0%      327.7      267.0 Met\n",
      "  Robust 10%        Fibre                     100.0%       37.3       30.0 Met\n",
      "  Robust 10%        Calcium                    98.0%      778.3      700.0 Met\n",
      "  Robust 10%        Iron                       98.0%       16.6       14.8 Met\n",
      "  Robust 10%        Zinc                      100.0%       10.5        7.0 Met\n",
      "  Robust 10%        Vit C                      99.7%       48.2       40.0 Met\n",
      "  Robust 10%        Vit D                      99.6%       13.3       10.0 Met\n",
      "  Robust 10%        Vit B12                   100.0%        6.9        1.5 Met\n",
      "  Robust 10%        Folate                    100.0%      261.2      200.0 Met\n",
      "  CC Bonferroni     Energy                    100.0%     2153.9     1800.0 Met\n",
      "  CC Bonferroni     Protein                   100.0%       77.5       45.0 Met\n",
      "  CC Bonferroni     Carbs                     100.0%      357.0      267.0 Met\n",
      "  CC Bonferroni     Fibre                     100.0%       40.8       30.0 Met\n",
      "  CC Bonferroni     Calcium                   100.0%      837.9      700.0 Met\n",
      "  CC Bonferroni     Iron                      100.0%       18.0       14.8 Met\n",
      "  CC Bonferroni     Zinc                      100.0%       11.4        7.0 Met\n",
      "  CC Bonferroni     Vit C                      99.6%       48.2       40.0 Met\n",
      "  CC Bonferroni     Vit D                      99.5%       13.3       10.0 Met\n",
      "  CC Bonferroni     Vit B12                   100.0%        6.9        1.5 Met\n",
      "  CC Bonferroni     Folate                    100.0%      281.0      200.0 Met\n",
      "  CC SOCP           Energy                     95.1%     2022.2     1800.0 Met\n",
      "  CC SOCP           Protein                   100.0%       73.4       45.0 Met\n",
      "  CC SOCP           Carbs                     100.0%      366.1      267.0 Met\n",
      "  CC SOCP           Fibre                     100.0%       40.1       30.0 Met\n",
      "  CC SOCP           Calcium                    95.3%      772.3      700.0 Met\n",
      "  CC SOCP           Iron                       94.6%       16.8       14.8 Met\n",
      "  CC SOCP           Zinc                      100.0%       10.3        7.0 Met\n",
      "  CC SOCP           Vit C                      94.8%       47.3       40.0 Met\n",
      "  CC SOCP           Vit D                      94.9%       11.8       10.0 Met\n",
      "  CC SOCP           Vit B12                   100.0%        6.3        1.5 Met\n",
      "  CC SOCP           Folate                     98.3%      227.7      200.0 Met\n",
      "\n",
      "  Male 19-64:\n",
      "  Layer             Nutrient               % meeting   Mean/day     Target\n",
      "  --------------------------------------------------------------------\n",
      "  Baseline          Energy                     50.4%     2299.2     2300.0 At risk\n",
      "  Baseline          Protein                   100.0%       77.0       55.5 Met\n",
      "  Baseline          Carbs                      96.2%      368.6      333.0 Met\n",
      "  Baseline          Fibre                     100.0%       39.2       30.0 Met\n",
      "  Baseline          Calcium                    68.1%      718.3      700.0 At risk\n",
      "  Baseline          Iron                      100.0%       16.1        8.7 Met\n",
      "  Baseline          Zinc                       97.1%       10.5        9.5 Met\n",
      "  Baseline          Vit C                     100.0%       50.7       40.0 Met\n",
      "  Baseline          Vit D                      99.7%       13.3       10.0 Met\n",
      "  Baseline          Vit B12                   100.0%        6.9        1.5 Met\n",
      "  Baseline          Folate                    100.0%      247.0      200.0 Met\n",
      "  Robust 10%        Energy                     99.1%     2555.0     2300.0 Met\n",
      "  Robust 10%        Protein                   100.0%       83.7       55.5 Met\n",
      "  Robust 10%        Carbs                     100.0%      398.7      333.0 Met\n",
      "  Robust 10%        Fibre                     100.0%       44.3       30.0 Met\n",
      "  Robust 10%        Calcium                    98.9%      794.1      700.0 Met\n",
      "  Robust 10%        Iron                      100.0%       17.9        8.7 Met\n",
      "  Robust 10%        Zinc                      100.0%       11.7        9.5 Met\n",
      "  Robust 10%        Vit C                     100.0%       50.8       40.0 Met\n",
      "  Robust 10%        Vit D                      99.7%       13.3       10.0 Met\n",
      "  Robust 10%        Vit B12                   100.0%        6.9        1.5 Met\n",
      "  Robust 10%        Folate                    100.0%      275.6      200.0 Met\n",
      "  CC Bonferroni     [Infeasible — no plan]\n",
      "  CC SOCP           Energy                     95.4%     2588.9     2300.0 Met\n",
      "  CC SOCP           Protein                   100.0%       91.1       55.5 Met\n",
      "  CC SOCP           Carbs                     100.0%      478.4      333.0 Met\n",
      "  CC SOCP           Fibre                     100.0%       49.9       30.0 Met\n",
      "  CC SOCP           Calcium                   100.0%      954.9      700.0 Met\n",
      "  CC SOCP           Iron                      100.0%       21.4        8.7 Met\n",
      "  CC SOCP           Zinc                      100.0%       12.9        9.5 Met\n",
      "  CC SOCP           Vit C                      95.0%       47.2       40.0 Met\n",
      "  CC SOCP           Vit D                      95.2%       11.8       10.0 Met\n",
      "  CC SOCP           Vit B12                   100.0%        6.2        1.5 Met\n",
      "  CC SOCP           Folate                    100.0%      284.8      200.0 Met\n",
      "\n",
      " At risk = adequacy below 75%  |  Met = adequacy ≥ 90%\n",
      "Energy/VitD at ~50% is expected: LP binds exactly at lower bound.\n",
      "CC layers (Bonferroni/SOCP) should show higher adequacy rates.\n"
     ]
    }
   ],
   "source": [
    "# CELL 12: Monte Carlo back-test — all 4 layers (key dissertation contribution)\n",
    "\n",
    "print(\"MONTE CARLO BACK-TEST — All 4 layers, 5000 draws, cv=10%\")\n",
    "print(\"Demonstrates that CC plans improve adequacy rates over Baseline.\")\n",
    "\n",
    "mc_results = {}\n",
    "for H, hn in [(1, 'Daily'), (7, 'Weekly')]:   # daily + weekly only (monthly same as weekly)\n",
    "    df_h_mc, _ = build_horizon(H)\n",
    "    print(f\"\\n── {hn.upper()} PLANS ──\")\n",
    "    for sex_label, t_day in SEX_SPECS:\n",
    "        print(f\"\\n  {sex_label}:\")\n",
    "        print(f\"  {'Layer':16s}  {'Nutrient':20s}  {'% meeting':>10}  \"\n",
    "              f\"{'Mean/day':>9}  {'Target':>9}\")\n",
    "        print(f\"  {'-'*68}\")\n",
    "        for layer in ALL_LAYERS:\n",
    "            r = results.get((hn, layer, sex_label))\n",
    "            if not r or r.get('plan') is None or len(r.get('plan', pd.DataFrame())) == 0:\n",
    "                print(f\"  {layer:16s}  [Infeasible — no plan]\")\n",
    "                continue\n",
    "            mc = monte_carlo(r['plan'], df_raw, t_day,\n",
    "                             n_sim=5000, cv=0.10, horizon_days=H)\n",
    "            mc_results[(hn, layer, sex_label)] = mc\n",
    "            if mc is not None:\n",
    "                for nut in mc.index:\n",
    "                    nm  = nut.split(' (')[0]\n",
    "                    pct = mc.loc[nut, 'pct_meeting']\n",
    "                    flag = ' At risk' if pct < 75 else (' Met' if pct >= 90 else '')\n",
    "                    print(f\"  {layer:16s}  {nm:20s}  {pct:>9.1f}%  \"\n",
    "                          f\"{mc.loc[nut,'mean_daily']:>9.1f}  \"\n",
    "                          f\"{mc.loc[nut,'target']:>9}{flag}\")\n",
    "\n",
    "print(\"\\n At risk = adequacy below 75%  |  Met = adequacy ≥ 90%\")\n",
    "print(\"Energy/VitD at ~50% is expected: LP binds exactly at lower bound.\")\n",
    "print(\"CC layers (Bonferroni/SOCP) should show higher adequacy rates.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "316a3af4-4b42-4c9d-ab55-1b3ff3f1cef6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Saved: chart_multi_horizon.png\n",
      "Saved: chart_frontier.png\n"
     ]
    }
   ],
   "source": [
    "# CELL 13: Charts\n",
    "\n",
    "matplotlib.use('Agg')  # change to '%matplotlib inline' in Jupyter if needed\n",
    "LCOL = {\n",
    "    'Baseline': '#1976D2', 'Robust 10%': '#2E7D32',\n",
    "    'CC Bonferroni': '#F57F17', 'CC SOCP': '#C62828'\n",
    "}\n",
    "hns = ['Daily', 'Weekly', 'Monthly']\n",
    "hds = {'Daily': 1, 'Weekly': 7, 'Monthly': 30}\n",
    "\n",
    "fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n",
    "fig.suptitle(\n",
    "    'Uncertainty-Aware Diet Optimisation — Results Summary\\n'\n",
    "    '104 UK whole foods (CoFID 2021) · Aldi UK May 2026 prices · PHE 2016 targets',\n",
    "    fontsize=13, y=1.01\n",
    ")\n",
    "xp = np.arange(3); w = 0.18\n",
    "\n",
    "# Panel A — Female cost by horizon × layer\n",
    "ax = axes[0, 0]\n",
    "for j, layer in enumerate(ALL_LAYERS):\n",
    "    costs = [\n",
    "        round(results.get((hn, layer, 'Female 19-50'), {}).get('cost', None) / hds[hn], 2)\n",
    "        if results.get((hn, layer, 'Female 19-50'), {}).get('cost') else 0\n",
    "        for hn in hns\n",
    "    ]\n",
    "    ax.bar(xp + j * w - 0.27, costs, w, label=layer, color=LCOL[layer], alpha=0.88)\n",
    "    for i, v in enumerate(costs):\n",
    "        if v > 0:\n",
    "            ax.text(xp[i] + j * w - 0.27, v + 0.01, f'£{v}', ha='center', fontsize=7)\n",
    "ax.set_xticks(xp); ax.set_xticklabels(hns)\n",
    "ax.set_ylabel('Daily-equivalent cost (£/day)')\n",
    "ax.set_title('(A) Female 19-50')\n",
    "ax.legend(fontsize=8); ax.grid(axis='y', alpha=0.3)\n",
    "\n",
    "# Panel B — Male cost by horizon × layer\n",
    "ax = axes[0, 1]\n",
    "for j, layer in enumerate(ALL_LAYERS):\n",
    "    costs = [\n",
    "        round(results.get((hn, layer, 'Male 19-64'), {}).get('cost', None) / hds[hn], 2)\n",
    "        if results.get((hn, layer, 'Male 19-64'), {}).get('cost') else 0\n",
    "        for hn in hns\n",
    "    ]\n",
    "    ax.bar(xp + j * w - 0.27, costs, w, label=layer, color=LCOL[layer], alpha=0.88)\n",
    "    for i, v in enumerate(costs):\n",
    "        if v > 0:\n",
    "            ax.text(xp[i] + j * w - 0.27, v + 0.01, f'£{v}', ha='center', fontsize=7)\n",
    "ax.set_xticks(xp); ax.set_xticklabels(hns)\n",
    "ax.set_ylabel('Daily-equivalent cost (£/day)')\n",
    "ax.set_title('(B) Male 19-64')\n",
    "ax.legend(fontsize=8); ax.grid(axis='y', alpha=0.3)\n",
    "ax.annotate('Male Bonferroni CC\\nstructurally infeasible\\n(energy ratio too narrow)',\n",
    "            xy=(0.35, 0.68), xycoords='axes fraction', fontsize=7, color='#F57F17',\n",
    "            bbox=dict(boxstyle='round,pad=0.3', fc='#FFF9C4', alpha=0.9))\n",
    "\n",
    "# Panel C — Price-of-robustness curve (weekly)\n",
    "ax = axes[1, 0]\n",
    "for sex, ls in [('Female', '-'), ('Male', '--')]:\n",
    "    for dp, col in [(5, '#1565C0'), (10, '#2E7D32'), (15, '#F57F17'), (20, '#B71C1C')]:\n",
    "        sub = weekly_rob_df[\n",
    "            (weekly_rob_df['Sex'] == sex) &\n",
    "            (weekly_rob_df['dev (%)'] == dp) &\n",
    "            (weekly_rob_df['Daily-equiv (£)'].notna())\n",
    "        ].sort_values('Γ (fraction)')\n",
    "        if len(sub):\n",
    "            ax.plot(sub['Γ (fraction)'], sub['Daily-equiv (£)'],\n",
    "                    linestyle=ls, color=col, marker='o', ms=5,\n",
    "                    label=f\"{sex[0]}, σ={dp}%\")\n",
    "ax.set_xlabel('Budget of uncertainty Γ (fraction of n foods)')\n",
    "ax.set_ylabel('Daily-equivalent cost (£/day)')\n",
    "ax.set_title('(C) Price of Robustness — Weekly\\n(Bertsimas & Sim 2004)')\n",
    "ax.legend(fontsize=7, ncol=2); ax.grid(alpha=0.3)\n",
    "\n",
    "# Panel D — Cost vs probability frontier\n",
    "ax = axes[1, 1]\n",
    "feas = frontier_df[frontier_df['£/day'].notna()]\n",
    "if len(feas):\n",
    "    ax.plot(feas['Confidence (%)'], feas['£/day'],\n",
    "            'o-', color='#C62828', lw=2, ms=8)\n",
    "    for _, row in feas.iterrows():\n",
    "        ax.annotate(f\"£{row['£/day']:.2f}\",\n",
    "                    (row['Confidence (%)'], row['£/day']),\n",
    "                    textcoords='offset points', xytext=(5, 5), fontsize=8)\n",
    "ax.axvline(95, color='grey', linestyle='--', alpha=0.6, label='α = 95%')\n",
    "ax.set_xlabel('Confidence level α (%)')\n",
    "ax.set_ylabel('Daily-equivalent cost (£/day)')\n",
    "ax.set_title('(D) Cost vs Probability-of-Adequacy\\nWeekly female · Bonferroni CC · cv=10%')\n",
    "ax.legend(fontsize=8); ax.grid(alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('chart_multi_horizon.png', dpi=130, bbox_inches='tight')\n",
    "print(\"\\nSaved: chart_multi_horizon.png\")\n",
    "\n",
    "# Standalone frontier chart\n",
    "fig2, ax2 = plt.subplots(figsize=(8, 5))\n",
    "if len(feas):\n",
    "    ax2.plot(feas['Confidence (%)'], feas['£/day'],\n",
    "             'o-', color='#C62828', lw=2.5, ms=9)\n",
    "    for _, row in feas.iterrows():\n",
    "        ax2.annotate(f\"£{row['£/day']:.2f}\",\n",
    "                     (row['Confidence (%)'], row['£/day']),\n",
    "                     textcoords='offset points', xytext=(6, 4), fontsize=9)\n",
    "ax2.axvline(95, color='grey', linestyle='--', alpha=0.6, label='α = 95% (chosen)')\n",
    "ax2.set_xlabel('Required confidence level α (%)', fontsize=12)\n",
    "ax2.set_ylabel('Daily-equivalent cost (£/day)', fontsize=12)\n",
    "ax2.set_title('Cost vs Probability-of-Adequacy Frontier\\n'\n",
    "              'Weekly female · Bonferroni CC · cv = 10%', fontsize=12)\n",
    "ax2.legend(); ax2.grid(alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig('chart_frontier.png', dpi=130)\n",
    "print(\"Saved: chart_frontier.png\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "2c4ebc3c-ec27-4f2d-b33e-c7f32047dcf0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Saving all outputs\n",
      "Saved: diet_results_final.xlsx\n",
      "PIPELINE COMPLETE\n",
      "Outputs:\n",
      "  diet_results_final.xlsx   — all results, plans, Monte Carlo\n",
      "  chart_multi_horizon.png   — 4-panel cost comparison\n",
      "  chart_frontier.png        — cost vs probability curve\n"
     ]
    }
   ],
   "source": [
    "# CELL 14: Save all outputs to Excel\n",
    "\n",
    "print(\"\\nSaving all outputs\")\n",
    "\n",
    "with pd.ExcelWriter('diet_results_final.xlsx', engine='openpyxl') as writer:\n",
    "\n",
    "    # Master comparison\n",
    "    comp_rows = []\n",
    "    for sex_label, _ in SEX_SPECS:\n",
    "        for H, hn in HORIZONS:\n",
    "            row = {'Sex': sex_label, 'Horizon': hn, 'Days': H}\n",
    "            for layer in ALL_LAYERS:\n",
    "                r    = results.get((hn, layer, sex_label), {})\n",
    "                cost = r.get('cost', None)\n",
    "                row[f'{layer} total (£)'] = cost\n",
    "                row[f'{layer} £/day']     = round(cost / H, 2)    if cost else None\n",
    "                row[f'{layer} £/week']    = round(cost / H * 7, 2)  if cost else None\n",
    "                row[f'{layer} £/month']   = round(cost / H * 30, 2) if cost else None\n",
    "                row[f'{layer} status']    = r.get('status', 'N/A')\n",
    "            comp_rows.append(row)\n",
    "    pd.DataFrame(comp_rows).to_excel(writer, sheet_name='Master_Comparison', index=False)\n",
    "    cost_df.to_excel(writer, sheet_name='Cost_Summary', index=False)\n",
    "    weekly_rob_df.to_excel(writer, sheet_name='Robust_Sweep_Weekly', index=False)\n",
    "    frontier_df.to_excel(writer, sheet_name='Frontier_Weekly_F', index=False)\n",
    "\n",
    "    # Individual food plans\n",
    "    for H, hn in HORIZONS:\n",
    "        for sex_label, _ in SEX_SPECS:\n",
    "            for layer in ALL_LAYERS:\n",
    "                r = results.get((hn, layer, sex_label))\n",
    "                if r and r.get('plan') is not None and len(r.get('plan', pd.DataFrame())) > 0:\n",
    "                    plan = r['plan'].copy()\n",
    "                    plan['Daily-equiv (g)'] = (plan['Grams'] / H).round(1)\n",
    "                    plan['Cost/day (£)']    = (plan['Cost (£)'] / H).round(3)\n",
    "                    sn = f\"{hn[:1]}_{sex_label[:1]}_{layer.replace(' ','_')[:9]}\"\n",
    "                    plan.to_excel(writer, sheet_name=sn, index=False)\n",
    "\n",
    "    # Meal plans\n",
    "    if len(meal_plan_F) > 0:\n",
    "        meal_plan_F.to_excel(writer, sheet_name='MealPlan_7day_Female', index=False)\n",
    "    if len(meal_plan_M) > 0:\n",
    "        meal_plan_M.to_excel(writer, sheet_name='MealPlan_7day_Male', index=False)\n",
    "\n",
    "    # Monte Carlo\n",
    "    mc_rows_out = []\n",
    "    for (hn, layer, sex_label), mc in mc_results.items():\n",
    "        if mc is not None:\n",
    "            mc2 = mc.copy()\n",
    "            mc2.insert(0, 'Horizon', hn)\n",
    "            mc2.insert(1, 'Layer',   layer)\n",
    "            mc2.insert(2, 'Sex',     sex_label)\n",
    "            mc2.index.name = 'Nutrient'\n",
    "            mc_rows_out.append(mc2.reset_index())\n",
    "    if mc_rows_out:\n",
    "        pd.concat(mc_rows_out, ignore_index=True).to_excel(\n",
    "            writer, sheet_name='Monte_Carlo_All_Layers', index=False)\n",
    "\n",
    "print(\"Saved: diet_results_final.xlsx\")\n",
    "print(\"PIPELINE COMPLETE\")\n",
    "print(\"Outputs:\")\n",
    "print(\"  diet_results_final.xlsx   — all results, plans, Monte Carlo\")\n",
    "print(\"  chart_multi_horizon.png   — 4-panel cost comparison\")\n",
    "print(\"  chart_frontier.png        — cost vs probability curve\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "83c95926-a92f-4db2-86bb-bbed61443526",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
